language: python

python: 3.5

# Use container based infrastructure
sudo: false

addons:
  apt:
    packages:
      - libenchant-dev

matrix:
  include:
    - python: '3.5'
      env: TOXENV=flake8
    - python: '3.6'
      env: TOXENV=py36-dj111-sqlite-cms35
    - python: '3.5'
      env: TOXENV=py35-dj111-sqlite-cms35
    - python: '3.5'
      env: TOXENV=py35-dj110-sqlite-cms34
    - python: '3.5'
      env: TOXENV=py35-dj19-sqlite-cms34
    - python: '3.5'
      env: TOXENV=py35-dj19-sqlite-cms34
    - python: '2.7'
      env: TOXENV=py27-dj111-sqlite-cms34
    - python: '2.7'
      env: TOXENV=py27-dj110-sqlite-cms34
    - python: '2.7'
      env: TOXENV=py27-dj19-sqlite-cms34
    - python: '3.5'
      env: TOXENV=py35-dj18-sqlite-cms34
    - python: '3.5'
      env: TOXENV=py35-dj18-sqlite-cms34
    - python: '2.7'
      env: TOXENV=py27-dj18-sqlite-cms34

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

before_script:
  - if [ "$FE" == 1 ]; then nvm install 6 && nvm use 6; fi
  - if [ "$FE" == 1 ]; then npm config set spin false; fi
  - if [ "$FE" == 1 ]; then npm install -g gulp@3.9.0; fi
  - if [ "$FE" == 1 ]; then npm install -g codeclimate-test-reporter; fi
  - if [ "$FE" == 1 ]; then npm install; fi

after_script:
  - codeclimate < tests/coverage/**/lcov.info

script:
  - tox -e $TOXENV

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
