# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

env:
  - CMD=./test

python:
  - 2.7
  - 2.6
  - 3.4
  - 3.3

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
    - env: CMD="flake8 aldryn_newsblog"
  fast_finish: true
  include:
    - python: 2.7
      env: CMD="flake8 aldryn_newsblog"

cache:
  directories:
    - $HOME/.pip-cache
    - $HOME/.wheelhouse

install:
  - pip wheel --wheel-dir $HOME/.wheelhouse --download-cache $HOME/.pip-cache -r test_requirements.txt
  - pip install --use-wheel --no-index --find-links=$HOME/.wheelhouse -r test_requirements.txt

script: $CMD

# TODO: Add coverage reporting
# after_success: coveralls
